buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22'
        classpath 'org.jetbrains.kotlin:kotlin-serialization:1.9.22'
        classpath 'org.jetbrains.compose:compose-gradle-plugin:1.6.11'
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}